name: CI/CD Pipeline with Self-Hosted Runner

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Image Build
        run: docker build -t barkinatici/app:latest .

      - name: Docker Image Push
        run: docker push barkinatici/app:latest


