name: cicd pipe

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Kodu Checkout Et
        uses: actions/checkout@v4.2.2

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Image Build
        run: docker build -t barkinatici/app:latest .

      - name: Docker Image Push
        run: docker push barkinatici/app:latest


#rke2 de master worker node ile cd kısmını hallet .